name: manufacturing_supply_chain
version: 1.0.0
config-version: 2
profile: manufacturing_supply_chain
model-paths: [models]
test-paths: [tests]
models:
  manufacturing_supply_chain:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
