-- 06 Quality & Machine Event Analysis
SELECT SUM(inspected_quantity) AS inspected_units, SUM(failed_quantity) AS failed_units, SUM(failed_quantity)*1.0/NULLIF(SUM(inspected_quantity),0) AS failure_rate FROM quality_inspections;
SELECT result, COUNT(*) AS inspections, SUM(inspected_quantity) AS inspected_units, SUM(failed_quantity) AS failed_units FROM quality_inspections GROUP BY result;
SELECT defect_type, COUNT(*) AS inspections, SUM(failed_quantity) AS failed_units, SUM(failed_quantity)*1.0/NULLIF(SUM(inspected_quantity),0) AS failure_rate FROM quality_inspections GROUP BY defect_type ORDER BY failure_rate DESC;
SELECT plant_id, SUM(inspected_quantity) AS inspected_units, SUM(failed_quantity) AS failed_units, SUM(failed_quantity)*1.0/NULLIF(SUM(inspected_quantity),0) AS failure_rate FROM quality_inspections GROUP BY plant_id ORDER BY failure_rate DESC;
SELECT product_id, SUM(failed_quantity)*1.0/NULLIF(SUM(inspected_quantity),0) AS failure_rate, SUM(failed_quantity) AS failed_units FROM quality_inspections GROUP BY product_id HAVING SUM(inspected_quantity)>=1000 ORDER BY failure_rate DESC;
SELECT SUBSTR(inspection_date,1,7) AS month, SUM(inspected_quantity) AS inspected_units, SUM(failed_quantity) AS failed_units, SUM(failed_quantity)*1.0/NULLIF(SUM(inspected_quantity),0) AS failure_rate FROM quality_inspections GROUP BY 1 ORDER BY 1;
SELECT event_type, severity, COUNT(*) AS events, SUM(duration_minutes) AS downtime_minutes, AVG(duration_minutes) AS avg_duration FROM machine_events GROUP BY event_type,severity ORDER BY downtime_minutes DESC;
SELECT plant_id, COUNT(*) AS events, SUM(duration_minutes) AS downtime_minutes, SUM(CASE WHEN severity IN ('High','Critical') THEN 1 ELSE 0 END) AS high_severity_events FROM machine_events GROUP BY plant_id ORDER BY downtime_minutes DESC;
SELECT event_type, COUNT(*) AS events, AVG(duration_minutes) AS avg_duration FROM machine_events GROUP BY event_type ORDER BY avg_duration DESC;
SELECT q.plant_id, q.failure_rate, m.downtime_minutes, m.high_severity_events FROM (SELECT plant_id,SUM(failed_quantity)*1.0/NULLIF(SUM(inspected_quantity),0) AS failure_rate FROM quality_inspections GROUP BY plant_id) q JOIN (SELECT plant_id,SUM(duration_minutes) AS downtime_minutes,SUM(CASE WHEN severity IN ('High','Critical') THEN 1 ELSE 0 END) AS high_severity_events FROM machine_events GROUP BY plant_id) m USING(plant_id) ORDER BY q.failure_rate DESC, m.downtime_minutes DESC;
